blog/urls.py
from django.urls import path
from .views import (
	homepage, 
	about,
	post_details, 
	PostCreateView, 
	PostUpdateView,
	PostDeleteView,
	UserPostCreateView
	#create_post
	)

app_name = 'blog'
urlpatterns = [
	path('', homepage.as_view(), name='blog-home'),
	path('user/<str:username>', UserPostCreateView.as_view(), name='blog-userblogs'),
	path('about/', about.as_view(), name='blog-about'),
	path('posts/<int:id>/', post_details.as_view(), name = 'blog-post'),
	path('posts/<int:pk>/update/', PostUpdateView.as_view(), name = 'blog-update'),
	path('posts/<int:pk>/delete/', PostDeleteView.as_view(), name = 'blog-delete'),
	path('post/new/', PostCreateView.as_view(), name='blog-new')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import error_404
# media imports
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("blog.urls")),
    path('', include("users.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
handler404 = error_404.as_view()

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Post(models.Model):
	title = models.CharField(max_length=100)
	content = models.TextField()
	date_posted = models.DateTimeField(default=timezone.now)
	author = models.ForeignKey(User, on_delete=models.CASCADE)


	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("blog:blog-post", kwargs = {"id":self.id})

blog/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms 
from .models import Post

class CreateNewPost(forms.ModelForm):

	class Meta:
		model = Post
		fields = ['title', 'content']

blog/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.views import View
from .models import Post
from django.contrib.auth.models import User
from .forms import CreateNewPost
from django.shortcuts import redirect
from django.contrib import messages
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

# Create your views here.

class homepage(View):
	template_name = 'blog/index.html'

	def get(self, request, *args, **kwargs):
		posts_list = Post.objects.all().order_by('-date_posted') # select *from table_name order by DESC

		page = request.GET.get('page', 1)
		paginator = Paginator(posts_list, 4)

		try:
			posts = paginator.page(page)
		except PageNotAnInteger: 
			posts = paginator.page(1)
		except EmptyPage:
			posts = paginator.num_pages()


		context = {
			"posts" : posts
		}
		
		#post = Post.objects.get(pk=1)
		#print('POST Details: ', dir(post.author))
		return render(request, self.template_name, context)


class UserPostCreateView(ListView):
	template_name = 'blog/users_posts.html'

	def get(self, request, *args, **kwargs):
		user = get_object_or_404(User, username=self.kwargs.get('username'))
		posts_list = Post.objects.filter(author=user).order_by('-date_posted') # select *from table_name order by DESC

		page = request.GET.get('page', 1)
		paginator = Paginator(posts_list, 4)

		try:
			posts = paginator.page(page)
		except PageNotAnInteger: 
			posts = paginator.page(1)
		except EmptyPage:
			posts = paginator.num_pages()

		context = {
			"posts" : posts,
			"username": self.kwargs.get('username'),
			"user_total_pages": posts_list.count()
		}
		#print("username here: ",context.get('username'))
		#print('user_total_pages: ',context.get('user_total_pages') )
		#post = Post.objects.get(pk=1)
		#print('POST Details: ', dir(post.author))
		return render(request, self.template_name, context)



class error_404(View):
	template_name = '404.html'

	def get(self, request, *args, **kwargs):
		return render(request, self.template_name)



class about(View):
	template_name = 'blog/about.html'

	def get(self, request, *args, **kwargs):
		return render(request, self.template_name, {})


class post_details(View):
	template_name = 'blog/posts.html'

	def get(self, request, id=id, *args, **kwargs):
		obj = Post.objects.get(pk=id)
		context = {"post":obj}
		return render(request, self.template_name, context)

# class create_post(View):
# 	template_name = 'blog/post_create.html'

# 	def get(self, request, *args, **kwargs):
# 		form = CreateNewPost()
# 		context = {"form":form}
# 		return render(request, self.template_name, context)


# 	def post(self, request, *args, **kwargs):
# 		form = CreateNewPost(request.POST or None, form.instance.author = Post.author)

# 		if form.is_valid():
# 			form.save()
# 			return redirect('blog:blog-home')

class PostCreateView(LoginRequiredMixin, CreateView):
	model = Post  
	fields = ['title', 'content']


	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)




class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = Post  
	fields = ['title', 'content']


	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)

	def test_func(self):
		post = self.get_object()
		if self.request.user == post.author:
			return True
		return False



class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):

	model = Post
	success_url  = '/'

	def test_func(self):
		post = self.get_object()
		if self.request.user == post.author:
			return True
		return False

blog/templates/blog/about.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>about</title>
</head>
<body>
	{% block content %}
		<h1>About Page</h1>
	{% endblock%}
</body>
</html>

blog/templates/blog/index.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>blog</title>
</head>
<body>

	{% block content %}
		{% for post in posts %}
			<article class="media content-section">
			  <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}"/>
			  <div class="media-body">
			    <div class="article-metadata">
			      <a class="mr-2" href="{% url 'blog:blog-userblogs' post.author %}"><b>{{post.author|title}}</b></a>
			      <small class="text-muted">{{post.date_posted|date:"F d, Y"}}</small>
			    </div>
			    <a style="font-size: 25px; text-decoration: none" href="{{ post.get_absolute_url }}">{{post.title}}</a>
			    <br>
			    <a style="text-decoration: none; color: black" class="article-content" href="{{ post.get_absolute_url }}">{{post.content|truncatewords:25}}</a>
			  </div>
			</article>
		{% endfor %}	

		{% if posts.has_other_pages %}
		    <nav>
		      <ul class="pagination justify-content-center mb-4">
		        {% if posts.has_previous %}
		          <li class="page-item">
		            <a class="page-link" href="?page={{ posts.previous_page_number }}" aria-label="Previous">
		              <span aria-hidden="true">&laquo;</span>
		            </a>
		          </li>
		        {% else %}
		          <li class="page-item disabled">
		              <span class="page-link" aria-hidden="true">&laquo;</span>
		          </li>
		        {% endif %}

		        {% for p in posts.paginator.page_range %}
		          {% if posts.number == p %}
		            <li class="page-item"><a class="page-link" style="color: red;" href="#">{{ p }}</a></li>
		          {% else %}
		            <li class="page-item"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
		          {% endif %}
		        {% endfor %}

		        {% if posts.has_next %}
		          <li class="page-item">
		            <a class="page-link" href="?page={{ posts.next_page_number }}" aria-label="Next">
		              <span aria-hidden="true">&raquo;</span>
		            </a>
		          </li>
		        {% else %}
		          <li class="page-item disabled">
		            <span class="page-link" aria-hidden="true">&raquo;</span>
		          </li>
		        {% endif %}
		     </ul>
		    </nav>
		{% endif %}
	{% endblock %}
</body>
</html>

blog/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}


{% block content %}
	<div class="content-section">
		<form action='.' method="POST"> {% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4 ">Delete Post</legend>
				<h2>Are you sure you want to delete the post "{{ post.title }}"</h2>
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
				<a class="btn btn-outline-secondary" href="{% url 'blog:blog-post' post.id %}">Cancel</a>
			</div>
		</form>
	</div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
	<div class="content-section">
		<form action='.' method="POST"> {% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4 ">New Blog Post</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Post</button>
			</div>
		</form>
	</div>
{% endblock %}

blog/templates/blog/posts.html
{% extends 'base.html' %}

	{% block content %}
			<article class="media content-section">
			  <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}"/>
			  <div class="media-body">
			    <div class="article-metadata">
			    	{% if post.author == user %}
			      		<a class="mr-2" href="{% url 'users-profile' %}">{{post.author}}</a>
			      	{% else %}
			      		<a class="mr-4" href="{% url 'blog:blog-userblogs' post.author %}"> <b>{{post.author|title}}</b></a>
			      	{% endif %}

			      <small class="text-muted">{{post.date_posted|date:"F d, Y"}}</small>
			      {% if post.author == user %}
			      	<div>
			      		<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'blog:blog-update' post.id %}">Update</a>
			      		<a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'blog:blog-delete' post.id %}">Delete</a>
			      	</div>
			      {% endif %}
			    </div>
			    <h2 class="article-title" >{{post.title}}</h2>
			    <p class="article-content">{{post.content}}</p>
			  </div>
			</article>	
	{% endblock %}

blog/templates/blog/users_posts.html
{% extends 'base.html' %}
{% block content %}
	<legend class="border-bottom mb-4 ">
		<h3>{{ username|title }}'s Blog Posts({{ user_total_pages }})</h3>
	</legend>

	{% for post in posts %}
		<article class="media content-section">
		  <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}"/>
		  <div class="media-body">
		    <div class="article-metadata">
		      <a:visited class="mr-2" href="#"><b>{{post.author|title}}</b></a>
		      <small class="text-muted">{{post.date_posted|date:"F d, Y"}}</small>
		    </div>
		    <a style="font-size: 25px; text-decoration: none" href="{{ post.get_absolute_url }}">{{post.title}}</a>
		    <p class="article-content">{{post.content|truncatewords:25}}</p>
		  </div>
		</article>
	{% endfor %}	

	{% if posts.has_other_pages %}
	    <nav>
	      <ul class="pagination justify-content-center mb-4">
	        {% if posts.has_previous %}
	          <li class="page-item">
	            <a class="page-link" href="?page={{ posts.previous_page_number }}" aria-label="Previous">
	              <span aria-hidden="true">&laquo;</span>
	            </a>
	          </li>
	        {% else %}
	          <li class="page-item disabled">
	              <span class="page-link" aria-hidden="true">&laquo;</span>
	          </li>
	        {% endif %}

	        {% for p in posts.paginator.page_range %}
	          {% if posts.number == p %}
	            <li class="page-item"><a class="page-link" style="color: red;" href="#">{{ p }}</a></li>
	          {% else %}
	            <li class="page-item"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
	          {% endif %}
	        {% endfor %}

	        {% if posts.has_next %}
	          <li class="page-item">
	            <a class="page-link" href="?page={{ posts.next_page_number }}" aria-label="Next">
	              <span aria-hidden="true">&raquo;</span>
	            </a>
	          </li>
	        {% else %}
	          <li class="page-item disabled">
	            <span class="page-link" aria-hidden="true">&raquo;</span>
	          </li>
	        {% endif %}
	     </ul>
	    </nav>
	{% endif %}
{% endblock %}