blog/urls.py
from django.urls import path
from .views import (
	homepage, 
	about,
	post_details, 
	PostCreateView, 
	PostUpdateView,
	PostDeleteView,
	UserPostCreateView
	#create_post
	)

app_name = 'blog'
urlpatterns = [
	path('', homepage.as_view(), name='blog-home'),
	path('user/<str:username>', UserPostCreateView.as_view(), name='blog-userblogs'),
	path('about/', about.as_view(), name='blog-about'),
	path('posts/<int:id>/', post_details.as_view(), name = 'blog-post'),
	path('posts/<int:pk>/update/', PostUpdateView.as_view(), name = 'blog-update'),
	path('posts/<int:pk>/delete/', PostDeleteView.as_view(), name = 'blog-delete'),
	path('post/new/', PostCreateView.as_view(), name='blog-new')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import error_404
# media imports
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("blog.urls")),
    path('', include("users.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
handler404 = error_404.as_view()

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    <title>Blog</title>
  </head>
  <body>

  	<!-- start navbar -->
  	<header class="site-header">
	    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
	      <div class="container">
	        <a class="navbar-brand mr-4" href="/">Isaac Blog</a>
	        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="navbar-toggler-icon"></span>
	        </button>
	        <div class="collapse navbar-collapse" id="navbarToggle">
	          <div class="navbar-nav mr-auto">
	            <a class="nav-item nav-link" href="{% url 'blog:blog-home' %}">Home</a>
	            <a class="nav-item nav-link" href="{% url 'blog:blog-about' %}">About</a>
	          </div>
	          <!-- Navbar Right Side -->	        
	          <div class="navbar-nav">
	          {% if user.is_authenticated %}
	          	<a class="nav-item nav-link" href="{% url 'blog:blog-new' %}">New Post</a>
	          	<a class="nav-item nav-link" href="{% url 'users-profile' %}">Profile</a>
	          	<a class="nav-item nav-link" href="{% url 'users-signout' %}">Sign Out</a>
	          {% else %}
	            <a class="nav-item nav-link" href="{% url 'users-signin'%}">Login</a>
	            <a class="nav-item nav-link" href="{% url 'users-register'%}">Register</a>
	          {% endif %}
	        </div>
	       </div>
	      </div>
	    </nav>
  	</header>
	<!--end of navbar  -->


  	<!-- main container  -->
	<main role="main" class="container">
	  <div class="row">
	    <div class="col-md-8">
	    	<!-- flash messages -->
	    	{% if messages %}
	    		{% for message in messages %}
	    			<div class="alert alert-{{message.tags}}">
	    				{{ message }}
	    			</div>
	    		{% endfor %}
	    	{% endif %}


	      {% block content %}
	      	<!-- inherited templates -->
	      {% endblock %}
	    </div>
	    <div class="col-md-4">
	      <div class="content-section">
	        <h3>Fast News</h3>
	        <p class='text-muted'>You can put any information here you'd like.
	          <ul class="list-group">
	            <li class="list-group-item list-group-item-light">Latest Posts</li>
	            <li class="list-group-item list-group-item-light">Announcements</li>
	            <li class="list-group-item list-group-item-light">Calendars</li>
	            <li class="list-group-item list-group-item-light">etc</li>
	          </ul>
	        </p>
	      </div>
	    </div>
	  </div>
	</main>





    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/navbar.html
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="/">Django Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="/">Home</a>
            <a class="nav-item nav-link" href="/about">About</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="#">Login</a>
            <a class="nav-item nav-link" href="#">Register</a>
          </div>
        </div>
      </div>
    </nav>
  </header>